<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE note [
<!ELEMENT tävling (skidåkare*, snö*, väder*, datum)>
<!ELEMENT datum (#PCDATA)>
<!ELEMENT skidåkare (vikt)>
<!ELEMENT vikt (#PCDATA)>
<!ELEMENT snö (luftfuktighet)>
<!ELEMENT luftfuktighet (#PCDATA)>
<!ELEMENT väder (temperatur)>
<!ELEMENT skidor (nr, skidåkare, fabrikat, spann, snötyp)>
<!ELEMENT valla (namn, typ)>
<!ELEMENT struktur (namn, grovlek)>
<!ATTLIST struktur namn ID #REQUIRED> 
<!ATTLIST valla namn ID #REQUIRED> 
<!ATTLIST skidor nr,skidåkare ID #REQUIRED>
<!ATTLIST tävling namn ID #REQUIRED>
<!ATTLIST skidåkare namn ID #REQUIRED>
<!ATTLIST snö typ ID #REQUIRED>
<!ATTLIST väder typ ID #REQUIRED>
]>

<root>
  <tävling namn="Oberstdorf">
    <skidåkare>Markus Hellner</skidåkare>
    <snö>Lös</snö>
    <väder>Varmt</väder>
    <datum>2021-02-21</datum>
  </tävling>
  <datum>
    #PCDATA
  <datum/>
  <skidåkare namn="Charlotte Kalla">
    <vikt>60kg</vikt>
  </skidåkare>
  <vikt>
    #PCDATA
  </vikt>
  <snö typ="Lös">
    <luftfuktighet>60%</luftfuktighet>
  </snö>
  <luftfuktighet>
    #PCDATA
  </luftfuktighet>  
  <väder typ="Extremt varmt">
    <temperatur>+15</temperatur>
  </väder>
</root>
